### ISSUE TITLE
Fix native UI on 3.14

### ISSUE THREAD

**Issue by camilasan** [nextcloud/desktop#7121]
Continues #7101

### ⚠️ TODO:

- [x] align text/icon in buttons
- [x] fix talk icon in activity list

![Screenshot 2024-09-13 at 11 31 38](https://github.com/user-attachments/assets/df97aa37-af11-4e1e-aa34-827ec6d8193a)

- [ ] remove black border from around the call notification

![Screenshot 2024-09-13 at 12 29 01](https://github.com/user-attachments/assets/3a9facd5-64e1-4920-808d-dca2d0df8d55)

- [ ] the icons for the call actions buttons like reply, are not showing.
