### ISSUE TITLE
Handling of windows compatible file names

### ISSUE THREAD

**Issue by Rello** [nextcloud/desktop#7668]
Scope
- An auto rename for new files will be implemented in all frontends
  - 1st local rename
  - 2nd upload/PUT/POST
- This applies if the "enforce windows compatible filenames" setting **is activated on the instance**
- There will not be any user dialog for the rename
- Standard rename rules will be implemented in all frontends (no fetched from server)
- Files will be renamed locally before uploading

---

Out of Scope
- Existing files - A concept will be drafted separately

---
Ruleset

- name with trailing/leading whitespace
- name ending with a "."
- names with not-allowed unicode char (https://docs.microsoft.com/windows/desktop/intl/unicode)
- names with https://docs.microsoft.com/windows/desktop/intl/surrogates-and-supplementary-characters
- replace every non-valid character with a "_"
- e.g. ".file" -> "_file"

---
**ToDo**
- [ ] Implement standard rules
- [ ] Auto rename new file before uploading
- [ ] Warning dialog for file extension change

**Comment by Rello** [comment]
https://github.com/nextcloud/desktop/issues/7668

**Comment by Rello** [comment]
iOS

https://github.com/nextcloud/ios/pull/3118
